### ISSUE TITLE
Missing Something 

### ISSUE THREAD

**Issue by rwgreene999** [RickStrahl/MarkdownMonsterAddinProjectTemplate#1]
I am not really sure how this works.  I installed both Markdown Monster Addin Project and Open In Markdown.  When I click the "Open IN MarkdownMonster it tells me "The executable file for MarkdownMonster does not exist". What am I missing?

**Comment by RickStrahl** [comment]
The template tries to automatically link to your Markdown Monster installation at `%localappdata%\Markdown Monster`. If you don't have MM installed or installed in a different location you will have to fix up the project references to compile.
