### ISSUE TITLE
The following link in the readme.md does not work

### ISSUE THREAD

**Issue by Smurf-IV** [RickStrahl/MarkdownMonsterAddinProjectTemplate#3]
![image](https://user-images.githubusercontent.com/2418812/71079903-06b2c400-2184-11ea-9a5b-5fdd85eaa83e.png)

**Comment by Smurf-IV** [comment]
Apologies, this needs to be transferred to the Monster project, not this addin

**Comment by RickStrahl** [comment]
Thanks. Fixed.
